---
version: 1.0.x.{build}
image: Visual Studio 2019
clone_depth: 10
build: off
notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
environment:
  matrix:
    - core: true
    - core: false
for:
-
  matrix:
    only:
      - core: true
  install:
    - pwsh: '"PowerShell Version: $($PSVersionTable.PSVersion)"'
    - pwsh: '& .\extras\install.ps1'
  test_script:
    - pwsh: 'Get-DscResource | ? ImplementedAs -eq "Binary" | ft Name, Module, Version'
    - pwsh: '& .\src\tests\pester.ps1'
-
  matrix:
    only:
      - core: false
  install:
    - ps: '"PowerShell Version: $($PSVersionTable.PSVersion)"'
    - ps: '& .\extras\install.ps1'
  test_script:
    - ps: '& .\src\tests\pester.ps1'
