name: nightly
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  module_cache: PSFramework, PSDscResources, AccessControlDSC, powershell-yaml, PSScriptAnalyzer

defaults:
  run:
    shell: powershell

jobs:
  spec:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, windows-2022]
        tag: [General, Unit]
        include:
          - tag: General
            results_file: General.Results.xml
          - tag: Unit
            results_file: Unit.Results.xml

    steps:
      - name: "checkout"
        uses: actions/checkout@v4

      - name: "install modules"
        uses: potatoqualitee/psmodulecache@v6.2.1
        with:
          shell: powershell
          modules-to-cache: PnP.PowerShell:1.11.0
          modules-to-cache-prerelease: PnP.PowerShell

      - name: Configure WinRM
        uses: ./.github/actions/configure-winrm

      - name: Run Unit Tests
        uses: ./.github/actions/run-unit-tests

  acceptance:
    runs-on: ${{ matrix.os }}
    needs: "spec"
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, windows-2022]
        tag: [Basic]
        pwshlib_source: [forge, git]
        include:
          - pwshlib_source: forge
            pwshlib_repo: "puppetlabs/pwshlib"
            pwshlib_ref: "latest" # Change to a specific version if desired
            results_file: Acceptance.Forge.Results.xml
          - pwshlib_source: git
            pwshlib_repo: "https://github.com/puppetlabs/ruby-pwsh.git" # Change to another fork if desired
            pwshlib_ref: main # Change to another branch if desired
            results_file: Acceptance.Git.Results.xml

    steps:
      - name: "checkout"
        uses: actions/checkout@v4

      - name: "install modules"
        uses: potatoqualitee/psmodulecache@v6.2.1
        with:
          shell: powershell
          modules-to-cache: PnP.PowerShell:1.11.0
          modules-to-cache-prerelease: PnP.PowerShell
          updatable: true

      - name: Install PDK
        uses: ./.github/actions/install-pdk

      - name: Configure WinRM
        uses: ./.github/actions/configure-winrm

      - name: Run Acceptance Tests
        uses: ./.github/actions/run-acceptance-tests
