name: "release"

on:
  workflow_dispatch:
    inputs:
      target:
        description: "The target for the release. This can be a commit sha or a branch."
        required: false
        default: "main"
        type: "string"
env:
  module_cache: PSFramework, PSDscResources, powershell-yaml, PSScriptAnalyzer, PlatyPS

jobs:
  release:
    name: "release"
    runs-on: "windows-latest"
    defaults:
      run:
        shell: "powershell"

    steps:

      - name: "checkout"
        uses: "actions/checkout@v4"
        with:
          ref: ${{ github.event.inputs.target }}
          clean: true
          fetch-depth: 0

      - name: "install modules"
        uses: potatoqualitee/psmodulecache@v6.1
        with:
          shell: powershell
          modules-to-cache: PSFramework, PSDscResources, powershell-yaml, PSDesiredStateConfiguration, PnP.PowerShell:1.11.0
          modules-to-cache-prerelease: PnP.PowerShell, PSDscResources, PSDesiredStateConfiguration

      - name: "get version"
        id: "get_version"
        run: |
          $DataFile = Import-PowerShellDataFile -Path .\src\Puppet.Dsc\puppet.dsc.psd1
          Set-Content -Path $ENV:GITHUB_OUTPUT -Value "version=$($DataFile.ModuleVersion)"

      - name: "create release"
        run: |
          gh release create ${{ steps.get_version.outputs.version }} --title ${{ steps.get_version.outputs.version }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "publish module"
        run: .\scripts\publish.ps1 -Publish
        env:
          GALLERY_TOKEN: ${{ secrets.GALLERY_TOKEN }}

  repuppetize:
    name: "re-puppetize modules"
    needs: release
    uses: ./.github/workflows/repuppetize.yml
    secrets: inherit
