name: "repuppetize"

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      module_name:
        description: |
          The name of the PowerShell module as it appears on the Forge.
        required: false

env:
  module_cache: PSFramework, PSDscResources, powershell-yaml

jobs:
  setup:
    name: "setup"
    runs-on: "windows-latest"
    outputs:
      module: ${{ steps.setup_matrix.outputs.module }}

    steps:

      - name: "checkout"
        uses: "actions/checkout@v4"

      - name: "install modules"
        uses: potatoqualitee/psmodulecache@v6.2.1
        with:
          shell: powershell
          modules-to-cache: PSFramework, PSDscResources, PnP.PowerShell:1.11.0
          modules-to-cache-prerelease: PnP.PowerShell

      - name: "setup matrix"
        id: "setup_matrix"
        shell: powershell
        run: |
          Import-Module -Name PSDesiredStateConfiguration -Force
          Install-Module -Name Puppet.Dsc -Force
          Import-Module -Name ./src/BuildMatrix/BuildMatrix.psd1 -Force

          $ModuleData = $ENV:MODULE_NAME
          if (!$ModuleData) {
            $ModuleData = Get-ModuleData -Path ./dsc_resources.yml -PuppetizedOnly
          }

          $ModuleData | ConvertTo-BuildMatrix | Set-BuildMatrix
        env:
          MODULE_NAME: ${{ github.event.inputs.module_name }}

  repuppetize:
    runs-on: "windows-latest"
    defaults:
      run:
        shell: powershell
    needs: "setup"
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJson(needs.setup.outputs.module) }}

    steps:

      - name: "checkout"
        uses: "actions/checkout@v4"

      - name: "install required modules"
        uses: potatoqualitee/psmodulecache@v6.2.1
        with:
          shell: powershell
          modules-to-cache: PSFramework, PSDscResources, PnP.PowerShell:1.11.0
          modules-to-cache-prerelease: PnP.PowerShell

      - name: Install PDK
        uses: ./.github/actions/install-pdk
      
      - name: Configure WinRM
        uses: ./.github/actions/configure-winrm

      - name: "update module"
        env:
          FORGE_TOKEN: ${{ secrets.FORGE_API_TOKEN }}
        run: |
          Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
          refreshenv
          Import-Module -Name PSDesiredStateConfiguration -Force
          Install-Module -Name Puppet.Dsc -Force
          $null = Get-Command PDK, Publish-NewDscModuleVersion

          $UpdateForgeDscModule = @{
            ForgeNameSpace = 'dsc'
            Name = '${{ matrix.module }}'
            LatestMajorVersionOnly = $true
            MaximumVersionCountToRebuild = 1
          }
          Update-ForgeDscModule @UpdateForgeDscModule -Verbose
